services:
  - type: web
    name: productos-crud
    runtime: java
    plan: free
    buildCommand: cd productos-crud && ./mvnw clean package -DskipTests
    startCommand: cd productos-crud && java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: productos-db
          property: connectionString

databases:
  - name: productos-db
    plan: free
    databaseName: productos
    user: productos_user
